#!/data/data/com.termux/files/usr/bin/bash

set -euo pipefail

REPO="${REPO:-midnightkoderr/llama.cpp-android}"
VARIANTS=(opencl hexagon)
declare -A VARIANT_DIR=( [opencl]=gpu [hexagon]=npu )
BASE_DIR="${HOME}/llama.cpp"
UPDATE=0
REVERT=0
UNINSTALL=0
KEEP_BACKUP=0
DRY_RUN=0
BACKUP=0
BACKUP_FILE=""
RESTORE=0
RESTORE_FILE=""

log()  { printf '\033[1;32m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33mWARN:\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

usage() {
  cat <<EOF
Usage: install.sh [options]

Installs both variants side by side under one base dir (no need to choose one):
  ${BASE_DIR}/gpu/   CPU + OpenCL (Adreno GPU)
  ${BASE_DIR}/npu/   CPU + OpenCL + Hexagon NPU (HTP)

Each variant dir has an env.sh — source it to put that variant on PATH for
the current shell session (see the summary printed after install).

  --update           Update both to the latest release
  --revert           Restore both from their backups
  --uninstall        Remove both installs (and their backups)
  --keep-backup      With --uninstall, keep the revert backups
  --dry-run          With --uninstall, list what would be removed, delete nothing
  --backup [file]    Zip ${BASE_DIR} into one archive
                     (default: ~/llama-cpp-backup-<timestamp>.zip)
  --restore <file>   Restore ${BASE_DIR} from a --backup archive
  -h, --help         Show this help

Env overrides: REPO
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --update)      UPDATE=1; shift ;;
    --revert)      REVERT=1; shift ;;
    --uninstall)   UNINSTALL=1; shift ;;
    --keep-backup) KEEP_BACKUP=1; shift ;;
    --dry-run)     DRY_RUN=1; shift ;;
    --backup)
      BACKUP=1
      if [[ $# -ge 2 && "$2" != -* ]]; then BACKUP_FILE="$2"; shift 2; else shift; fi
      ;;
    --restore)
      RESTORE=1
      [[ $# -ge 2 ]] || die "--restore requires a path to a backup zip"
      RESTORE_FILE="$2"; shift 2
      ;;
    -h|--help)     usage; exit 0 ;;
    *) die "Unknown argument: $1  (try --help)" ;;
  esac
done

shopt -s nullglob

for t in curl tar; do
  command -v "$t" >/dev/null 2>&1 || die "Missing: ${t}"
done

dir_for()    { printf '%s/%s' "${BASE_DIR}" "${VARIANT_DIR[$1]}"; }
backup_for() { printf '%s/.llama.cpp-bin-backup-%s' "${HOME}" "$1"; }

# Writes an env.sh inside a variant dir. Source it (don't execute it) to put
# that variant's tools on PATH for the current shell — sourcing both variants
# in one session just means whichever was sourced last wins on PATH, since
# both ship binaries with the same names.
write_env_script() {
  local variant="$1" vdir="$2" name="${VARIANT_DIR[$1]}"
  {
    printf '#!/usr/bin/env bash\n'
    printf '# Generated by llama-install. Source this, don'"'"'t run it:\n'
    printf '#   source %s/env.sh\n' "${vdir}"
    printf 'LLAMA_CPP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"\n'
    printf 'export LD_LIBRARY_PATH="${LLAMA_CPP_DIR}/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"\n'
    if [[ "${variant}" == "hexagon" ]]; then
      printf 'export ADSP_LIBRARY_PATH="${LLAMA_CPP_DIR}/lib"\n'
    fi
    printf 'export PATH="${LLAMA_CPP_DIR}/bin:${PATH}"\n'
    printf 'echo "llama.cpp (%s) on PATH for this shell -- try: llama-cli --help"\n' "${name}"
  } > "${vdir}/env.sh"
  chmod +x "${vdir}/env.sh"
}

# Writes a run.sh inside a variant dir: `run.sh <model.gguf> [llama-cli args...]`
# with per-variant defaults, overridable via env vars, no env.sh sourcing needed.
write_run_script() {
  local variant="$1" vdir="$2"
  case "${variant}" in
    hexagon)
      cat > "${vdir}/run.sh" <<'RUNEOF'
#!/usr/bin/env bash
set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
[[ $# -ge 1 ]] || { echo "Usage: $(basename "$0") <model.gguf> [llama-cli args...]" >&2; exit 1; }
MODEL="$1"; shift
source "${DIR}/env.sh" >/dev/null

# 8 Gen 3 -> Hexagon v75, 7+ Gen 3 -> Hexagon v73 (auto-selected). Override
# with e.g. NGL=99 CTX=8192 ./run.sh model.gguf
NGL="${NGL:-99}"
CTX="${CTX:-4096}"
exec llama-cli -m "${MODEL}" --device HTP0 -ngl "${NGL}" -c "${CTX}" "$@"
RUNEOF
      ;;
    opencl)
      cat > "${vdir}/run.sh" <<'RUNEOF'
#!/usr/bin/env bash
set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
[[ $# -ge 1 ]] || { echo "Usage: $(basename "$0") <model.gguf> [llama-cli args...]" >&2; exit 1; }
MODEL="$1"; shift
source "${DIR}/env.sh" >/dev/null

# See docs/USAGE.md for per-SoC values, e.g.:
#   SD 8 Gen 3:  CORES=2-7 THREADS=4 ./run.sh model.gguf
#   SD 7+ Gen 3: CORES=3-7 THREADS=3 ./run.sh model.gguf
NGL="${NGL:-28}"
THREADS="${THREADS:-4}"
CTX="${CTX:-4096}"
if [[ -n "${CORES:-}" ]] && command -v taskset >/dev/null 2>&1; then
  exec taskset -c "${CORES}" llama-cli -m "${MODEL}" -t "${THREADS}" -ngl "${NGL}" -c "${CTX}" "$@"
fi
exec llama-cli -m "${MODEL}" -t "${THREADS}" -ngl "${NGL}" -c "${CTX}" "$@"
RUNEOF
      ;;
  esac
  chmod +x "${vdir}/run.sh"
}

# cpu/ isn't a separately downloaded package — it reuses the gpu build's
# binaries (a perfectly good CPU-only binary via -ngl 0), so it's created
# alongside gpu/ rather than tracked as its own variant.
write_cpu_helpers() {
  local cpu_dir="${BASE_DIR}/cpu"
  mkdir -p "${cpu_dir}"

  cat > "${cpu_dir}/env.sh" <<'ENVEOF'
#!/usr/bin/env bash
# Generated by llama-install. Source this, don't run it. Reuses the gpu
# build's binaries in CPU-only mode -- there's no separate cpu package.
LLAMA_CPP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../gpu" && pwd)"
export LD_LIBRARY_PATH="${LLAMA_CPP_DIR}/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
export PATH="${LLAMA_CPP_DIR}/bin:${PATH}"
echo "llama.cpp (cpu, via gpu build) on PATH for this shell -- try: llama-cli --help"
ENVEOF
  chmod +x "${cpu_dir}/env.sh"

  cat > "${cpu_dir}/run.sh" <<'RUNEOF'
#!/usr/bin/env bash
set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
[[ $# -ge 1 ]] || { echo "Usage: $(basename "$0") <model.gguf> [llama-cli args...]" >&2; exit 1; }
MODEL="$1"; shift
source "${DIR}/env.sh" >/dev/null

# See docs/USAGE.md for per-SoC P-core ranges, e.g.:
#   SD 8 Gen 3:  CORES=2-7 THREADS=6 ./run.sh model.gguf
#   SD 7+ Gen 3: CORES=3-7 THREADS=5 ./run.sh model.gguf
THREADS="${THREADS:-6}"
CTX="${CTX:-2048}"
if [[ -n "${CORES:-}" ]] && command -v taskset >/dev/null 2>&1; then
  exec taskset -c "${CORES}" llama-cli -m "${MODEL}" -t "${THREADS}" -ngl 0 -c "${CTX}" "$@"
fi
exec llama-cli -m "${MODEL}" -t "${THREADS}" -ngl 0 -c "${CTX}" "$@"
RUNEOF
  chmod +x "${cpu_dir}/run.sh"
}

# ── uninstall ─────────────────────────────────────────────────────────────────
if [[ "${UNINSTALL}" == "1" ]]; then
  [[ "${DRY_RUN}" == "1" ]] && log "DRY RUN — nothing will be deleted"

  rm_path() {
    local p="$1"
    [[ -e "$p" || -L "$p" ]] || return 0
    if [[ "${DRY_RUN}" == "1" ]]; then
      printf '    remove %s\n' "$p"
    else
      rm -rf "$p"
    fi
    removed=$((removed + 1))
  }

  removed=0
  for VARIANT in "${VARIANTS[@]}"; do
    VDIR="$(dir_for "${VARIANT}")"
    BACKUP_DIR="$(backup_for "${VARIANT}")"

    if [[ ! -d "${VDIR}" ]]; then
      warn "${VARIANT}: not installed — skipping"
      continue
    fi

    tag="unknown"
    [[ -f "${VDIR}/lib/llama-cpp.version" ]] && tag=$(cat "${VDIR}/lib/llama-cpp.version")
    log "Uninstalling ${VARIANT} (${tag}) from ${VDIR}"

    rm_path "${VDIR}"
    [[ "${KEEP_BACKUP}" == "0" ]] && rm_path "${BACKUP_DIR}"

    # cpu/ has no binaries of its own — it's a wrapper around gpu/, so it
    # goes when gpu does.
    [[ "${VARIANT}" == "opencl" ]] && rm_path "${BASE_DIR}/cpu"
  done

  if [[ -d "${BASE_DIR}" && -z "$(ls -A "${BASE_DIR}" 2>/dev/null)" ]]; then
    if [[ "${DRY_RUN}" == "1" ]]; then
      printf '    rmdir  %s (empty)\n' "${BASE_DIR}"
    else
      rmdir "${BASE_DIR}" 2>/dev/null || true
    fi
  fi

  if [[ "${removed}" == "0" ]]; then
    warn "Nothing found to remove (already uninstalled?)"
  else
    log "Done — removed ${removed} item(s)."
  fi

  exit 0
fi

# ── backup ────────────────────────────────────────────────────────────────────
if [[ "${BACKUP}" == "1" ]]; then
  command -v zip >/dev/null 2>&1 || die "Missing: zip  (install with: pkg install zip)"
  [[ -n "${BACKUP_FILE}" ]] || BACKUP_FILE="${HOME}/llama-cpp-backup-$(date +%Y%m%d-%H%M%S).zip"

  [[ -d "${BASE_DIR}" ]] || die "Nothing installed to back up"

  log "Backing up: $(basename "${BASE_DIR}")"
  ( cd "${HOME}" && zip -rq "${BACKUP_FILE}" "$(basename "${BASE_DIR}")" )
  log "Backup written to ${BACKUP_FILE}"
  exit 0
fi

# ── restore ───────────────────────────────────────────────────────────────────
if [[ "${RESTORE}" == "1" ]]; then
  command -v unzip >/dev/null 2>&1 || die "Missing: unzip  (install with: pkg install unzip)"
  [[ -f "${RESTORE_FILE}" ]] || die "Backup file not found: ${RESTORE_FILE}"

  log "Restoring ${RESTORE_FILE} into ${HOME}"
  unzip -oq "${RESTORE_FILE}" -d "${HOME}"

  for VARIANT in "${VARIANTS[@]}"; do
    VDIR="$(dir_for "${VARIANT}")"
    [[ -d "${VDIR}/bin" ]] && chmod +x "${VDIR}/bin"/llama-* 2>/dev/null || true
  done
  log "Restore complete."
  exit 0
fi

# ── revert ────────────────────────────────────────────────────────────────────
if [[ "${REVERT}" == "1" ]]; then
  for VARIANT in "${VARIANTS[@]}"; do
    VDIR="$(dir_for "${VARIANT}")"
    INSTALL_DIR="${VDIR}/bin"
    LIB_DIR="${VDIR}/lib"
    BACKUP_DIR="$(backup_for "${VARIANT}")"

    if [[ ! -d "${BACKUP_DIR}" ]]; then
      warn "${VARIANT}: no backup found in ${BACKUP_DIR} — skipping"
      continue
    fi

    prev="unknown"
    [[ -f "${BACKUP_DIR}/llama-cpp.version" ]] && prev=$(cat "${BACKUP_DIR}/llama-cpp.version")
    log "${VARIANT}: reverting to ${prev}"

    mkdir -p "${INSTALL_DIR}" "${LIB_DIR}"
    cp "${BACKUP_DIR}"/bin/* "${INSTALL_DIR}/" 2>/dev/null || die "${VARIANT}: backup has no binaries"
    cp "${BACKUP_DIR}"/lib/*.so "${LIB_DIR}/" 2>/dev/null || true
    [[ -f "${BACKUP_DIR}/llama-cpp.version" ]] && cp "${BACKUP_DIR}/llama-cpp.version" "${LIB_DIR}/llama-cpp.version"
    chmod +x "${INSTALL_DIR}"/llama-* 2>/dev/null || true
    [[ -f "${VDIR}/env.sh" ]] || write_env_script "${VARIANT}" "${VDIR}"
    [[ -f "${VDIR}/run.sh" ]] || write_run_script "${VARIANT}" "${VDIR}"
    if [[ "${VARIANT}" == "opencl" && ! -f "${BASE_DIR}/cpu/run.sh" ]]; then
      write_cpu_helpers
    fi
    rm -rf "${BACKUP_DIR}"
    log "${VARIANT}: reverted to ${prev}"
  done
  exit 0
fi

# ── fetch release info (once, shared by both variants) ────────────────────────
log "Fetching latest release info for ${REPO}"
release=$(curl -fsSL "https://api.github.com/repos/${REPO}/releases/latest")
tag=$(printf '%s' "${release}" | grep '"tag_name"' | head -n1 | sed 's/.*"tag_name": *"\(.*\)".*/\1/')
[[ -n "${tag}" ]] || die "Could not parse release tag — does the repo have any releases?"
log "Latest release: ${tag}"

for VARIANT in "${VARIANTS[@]}"; do
  VDIR="$(dir_for "${VARIANT}")"
  INSTALL_DIR="${VDIR}/bin"
  LIB_DIR="${VDIR}/lib"
  VERSION_FILE="${LIB_DIR}/llama-cpp.version"
  BACKUP_DIR="$(backup_for "${VARIANT}")"

  url=$(printf '%s' "${release}" | grep '"browser_download_url"' | grep '\.tar\.gz"' \
          | grep -- "-${VARIANT}-" | head -n1 | sed 's/.*"browser_download_url": *"\(.*\)".*/\1/')
  sha_url=$(printf '%s' "${release}" | grep '"browser_download_url"' | grep '\.tar\.gz\.sha256"' \
          | grep -- "-${VARIANT}-" | head -n1 | sed 's/.*"browser_download_url": *"\(.*\)".*/\1/')
  [[ -n "${url}" ]] || die "No '${VARIANT}' .tar.gz asset in release ${tag}"

  if [[ "${UPDATE}" == "1" ]]; then
    current="none"
    [[ -f "${VERSION_FILE}" ]] && current=$(cat "${VERSION_FILE}")
    if [[ "${current}" == "${tag}" ]]; then
      log "${VARIANT}: already up to date (${tag})"
      continue
    fi
    log "${VARIANT}: updating ${current} → ${tag}"
    if [[ -f "${INSTALL_DIR}/llama-cli" ]]; then
      rm -rf "${BACKUP_DIR}"
      mkdir -p "${BACKUP_DIR}/bin" "${BACKUP_DIR}/lib"
      for b in "${INSTALL_DIR}"/llama-*; do [[ -f "$b" ]] && cp "$b" "${BACKUP_DIR}/bin/"; done
      for l in "${LIB_DIR}"/*.so;     do [[ -f "$l" ]] && cp "$l" "${BACKUP_DIR}/lib/"; done
      [[ -f "${VERSION_FILE}" ]] && cp "${VERSION_FILE}" "${BACKUP_DIR}/"
    fi
  fi

  log "${VARIANT}: downloading $(basename "${url}")"
  mkdir -p "${INSTALL_DIR}" "${LIB_DIR}"
  tmp=$(mktemp -d)

  curl -fsSL --progress-bar "${url}" -o "${tmp}/llama.tar.gz"

  if [[ -n "${sha_url}" ]] && command -v sha256sum >/dev/null 2>&1; then
    curl -fsSL "${sha_url}" -o "${tmp}/llama.tar.gz.sha256"
    expected=$(awk '{print $1}' "${tmp}/llama.tar.gz.sha256")
    actual=$(sha256sum "${tmp}/llama.tar.gz" | awk '{print $1}')
    [[ "${expected}" == "${actual}" ]] || die "${VARIANT}: checksum mismatch (expected ${expected}, got ${actual})"
  fi

  tar -xzf "${tmp}/llama.tar.gz" -C "${tmp}"
  [[ -d "${tmp}/bin" && -d "${tmp}/lib" ]] || die "${VARIANT}: unexpected archive layout (no bin/ + lib/)"

  bins=( "${tmp}"/bin/llama-* )
  [[ ${#bins[@]} -gt 0 ]] || die "${VARIANT}: no llama-* binaries found in archive"
  cp "${bins[@]}" "${INSTALL_DIR}/"

  libs=( "${tmp}"/lib/*.so )
  [[ ${#libs[@]} -gt 0 ]] && cp "${libs[@]}" "${LIB_DIR}/"

  chmod +x "${INSTALL_DIR}"/llama-* 2>/dev/null || true
  printf '%s' "${tag}" > "${VERSION_FILE}"
  rm -rf "${tmp}"

  write_env_script "${VARIANT}" "${VDIR}"
  write_run_script "${VARIANT}" "${VDIR}"
  [[ "${VARIANT}" == "opencl" ]] && write_cpu_helpers

  log "${VARIANT}: installed → ${VDIR}"
done

GPU_DIR="$(dir_for opencl)"
NPU_DIR="$(dir_for hexagon)"
CPU_DIR="${BASE_DIR}/cpu"

cat <<EOF

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  llama.cpp ${tag} installed — both variants, side by side
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ${GPU_DIR}   CPU + OpenCL (Adreno GPU)
  ${NPU_DIR}   CPU + OpenCL + Hexagon NPU (HTP)
  ${CPU_DIR}   CPU only (reuses the gpu build, -ngl 0)

── Quick start: run.sh <model.gguf> [llama-cli args...] ─
  ${NPU_DIR}/run.sh model-Q4_0.gguf -p "Hello"
  ${GPU_DIR}/run.sh model.gguf -p "Hello"
  ${CPU_DIR}/run.sh model.gguf -p "Hello"

  Defaults are tunable via env vars, e.g.:
    CORES=2-7 THREADS=4 ${GPU_DIR}/run.sh model.gguf
  See docs/USAGE.md for per-SoC CORES/THREADS values.

── Manual: source env.sh, then call llama-cli directly ──
Each variant has its own env.sh. Source (not run) the one you want for this
shell session — it puts that variant's tools on plain PATH (llama-cli,
llama-server, ...). Sourcing more than one in a session just means whichever
you source last wins, since they all ship binaries with the same names.

  source ${NPU_DIR}/env.sh
  llama-cli -m model-Q4_0.gguf --device HTP0 -ngl 99 -c 4096 -p "Hello"

  source ${GPU_DIR}/env.sh
  taskset -c 2-7 llama-cli -m model.gguf -t 4 -ngl 28 -c 4096 -p "Hello"

── Server (OpenAI-compatible API) ───────────────────────
  llama-server -m model.gguf --host 0.0.0.0 --port 8080 --device HTP0 -ngl 99
  llama-server -m model.gguf --host 0.0.0.0 --port 8080 -t 4 -ngl 28 -c 4096

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EOF
