#!/data/data/com.termux/files/usr/bin/bash

set -euo pipefail

REPO="${REPO:-midnightkoderr/llama.cpp-android}"
declare -A VARIANT_DIR=( [opencl]=gpu [hexagon]=npu )
BASE_DIR="${HOME}/llama.cpp"
SELECT="all"   # cpu|gpu|npu|all
UPDATE=0
REVERT=0
UNINSTALL=0
KEEP_BACKUP=0
DRY_RUN=0
BACKUP=0
BACKUP_FILE=""
RESTORE=0
RESTORE_FILE=""

log()  { printf '\033[1;32m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33mWARN:\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

usage() {
  cat <<EOF
Usage: install.sh [cpu|gpu|npu|all] [options]

Installs one target, or all three side by side under one base dir (default
if none is given: all):
  ${BASE_DIR}/gpu/   CPU + OpenCL (Adreno GPU)
  ${BASE_DIR}/npu/   CPU + OpenCL + Hexagon NPU (HTP)
  ${BASE_DIR}/cpu/   CPU only — reuses the gpu build's binaries (-ngl 0),
                     no separate package

Each variant dir has an env.sh — source it to put that variant on PATH for
the current shell session (see the summary printed after install).

  cpu|gpu|npu|all    Which to install/update/uninstall/revert (default: all)
  --update           Update to the latest release
  --revert           Restore from backup
  --uninstall        Remove the install (and its backup)
  --keep-backup      With --uninstall, keep the revert backups
  --dry-run          With --uninstall, list what would be removed, delete nothing
  --backup [file]    Zip ${BASE_DIR} into one archive
                     (default: ~/llama-cpp-backup-<timestamp>.zip)
  --restore <file>   Restore ${BASE_DIR} from a --backup archive
  -h, --help         Show this help

Env overrides: REPO
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    cpu|gpu|npu|all) SELECT="$1"; shift ;;
    --update)      UPDATE=1; shift ;;
    --revert)      REVERT=1; shift ;;
    --uninstall)   UNINSTALL=1; shift ;;
    --keep-backup) KEEP_BACKUP=1; shift ;;
    --dry-run)     DRY_RUN=1; shift ;;
    --backup)
      BACKUP=1
      if [[ $# -ge 2 && "$2" != -* ]]; then BACKUP_FILE="$2"; shift 2; else shift; fi
      ;;
    --restore)
      RESTORE=1
      [[ $# -ge 2 ]] || die "--restore requires a path to a backup zip"
      RESTORE_FILE="$2"; shift 2
      ;;
    -h|--help)     usage; exit 0 ;;
    *) die "Unknown argument: $1  (try --help)" ;;
  esac
done

shopt -s nullglob

for t in curl tar; do
  command -v "$t" >/dev/null 2>&1 || die "Missing: ${t}"
done

case "${SELECT}" in
  all) VARIANTS=(opencl hexagon) ;;
  gpu) VARIANTS=(opencl) ;;
  npu) VARIANTS=(hexagon) ;;
  cpu)
    # cpu/ has no binaries of its own — it reuses the gpu build's, so
    # installing/updating/reverting "cpu" pulls in the gpu variant too.
    VARIANTS=(opencl)
    [[ "${UNINSTALL}" == "1" ]] || log "cpu reuses the gpu build's binaries — including gpu"
    ;;
esac

dir_for() { printf '%s/%s' "${BASE_DIR}" "${VARIANT_DIR[$1]}"; }

# Where a release VARIANT's binaries actually land. Normally that's dir_for()
# (gpu/npu), but a standalone "cpu" selection has no gpu/ at all — the opencl
# download goes straight into cpu/ instead of being a wrapper around gpu/.
vdir_for_variant() {
  if [[ "$1" == "opencl" && "${SELECT}" == "cpu" ]]; then
    printf '%s/cpu' "${BASE_DIR}"
  else
    dir_for "$1"
  fi
}

backup_for() { printf '%s/.llama.cpp-bin-backup-%s' "${HOME}" "$1"; }

# Writes an env.sh inside a dir. Source it (don't execute it) to put that
# build's tools on PATH for the current shell — sourcing more than one in a
# session just means whichever was sourced last wins on PATH, since they all
# ship binaries with the same names. `libs_subdir` lets env.sh point at
# another directory's bin/lib (used when cpu/ reuses gpu/'s binaries instead
# of shipping its own).
write_env_script() {
  local variant="$1" vdir="$2" label="$3" libs_subdir="${4:-}"
  {
    printf '#!/usr/bin/env bash\n'
    printf '# Generated by llama-install. Source this, don'"'"'t run it:\n'
    printf '#   source %s/env.sh\n' "${vdir}"
    if [[ -n "${libs_subdir}" ]]; then
      printf 'LLAMA_CPP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/%s" && pwd)"\n' "${libs_subdir}"
    else
      printf 'LLAMA_CPP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"\n'
    fi
    printf 'export LD_LIBRARY_PATH="${LLAMA_CPP_DIR}/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"\n'
    if [[ "${variant}" == "hexagon" ]]; then
      printf 'export ADSP_LIBRARY_PATH="${LLAMA_CPP_DIR}/lib"\n'
    fi
    printf 'export PATH="${LLAMA_CPP_DIR}/bin:${PATH}"\n'
    printf 'echo "llama.cpp (%s) on PATH for this shell -- try: llama-cli --help"\n' "${label}"
  } > "${vdir}/env.sh"
  chmod +x "${vdir}/env.sh"
}

# Writes a run.sh inside a dir: `run.sh <model.gguf> [llama-cli args...]` with
# per-kind defaults, overridable via env vars, no env.sh sourcing needed.
# kind is hexagon|opencl|cpu — "cpu" forces -ngl 0 regardless of which
# binaries env.sh in the same dir actually points at.
write_run_script() {
  local kind="$1" vdir="$2"
  case "${kind}" in
    hexagon)
      cat > "${vdir}/run.sh" <<'RUNEOF'
#!/usr/bin/env bash
set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
[[ $# -ge 1 ]] || { echo "Usage: $(basename "$0") <model.gguf> [llama-cli args...]" >&2; exit 1; }
MODEL="$1"; shift
source "${DIR}/env.sh" >/dev/null

# 8 Gen 3 -> Hexagon v75, 7+ Gen 3 -> Hexagon v73 (auto-selected). Override
# with e.g. NGL=99 CTX=8192 ./run.sh model.gguf
NGL="${NGL:-99}"
CTX="${CTX:-4096}"
UBATCH="${UBATCH:-256}"
export GGML_HEXAGON_NDEV=1

exec llama-cli -m "${MODEL_Q4_0}.gguf" \
  --no-mmap \
  --flash-attn auto \
  --device HTP0 \
  -ngl "${NGL}" \
  -c "${CTX}" \
  -ub "${UBATCH}" \
  -b "${UBATCH}" \
  "$@"
RUNEOF
      ;;
    opencl)
      cat > "${vdir}/run.sh" <<'RUNEOF'
#!/usr/bin/env bash
set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
[[ $# -ge 1 ]] || { echo "Usage: $(basename "$0") <model.gguf> [llama-cli args...]" >&2; exit 1; }
MODEL="$1"; shift
source "${DIR}/env.sh" >/dev/null

# See docs/USAGE.md for per-SoC values, e.g.:
#   SD 8 Gen 3:  CORES=2-7 THREADS=4 ./run.sh model.gguf
#   SD 7+ Gen 3: CORES=3-7 THREADS=3 ./run.sh model.gguf
NGL="${NGL:-28}"
THREADS="${THREADS:-4}"
CTX="${CTX:-4096}"
if [[ -n "${CORES:-}" ]] && command -v taskset >/dev/null 2>&1; then
  exec taskset -c "${CORES}" llama-cli \
    -m "${MODEL}" \
    --no-mmap \
    --flash-attn auto \
    -t "${THREADS}" \
    -ngl "${NGL}" \
    -c "${CTX}" "$@"
fi
exec llama-cli -m "${MODEL}" \
  -t "${THREADS}" \
  --no-mmap \
  --flash-attn auto \
  -ngl "${NGL}" \
  -c "${CTX}" "$@"
RUNEOF
      ;;
    cpu)
      cat > "${vdir}/run.sh" <<'RUNEOF'
#!/usr/bin/env bash
set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
[[ $# -ge 1 ]] || { echo "Usage: $(basename "$0") <model.gguf> [llama-cli args...]" >&2; exit 1; }
MODEL="$1"; shift
source "${DIR}/env.sh" >/dev/null

# See docs/USAGE.md for per-SoC P-core ranges, e.g.:
#   SD 8 Gen 3:  CORES=2-7 THREADS=6 ./run.sh model.gguf
#   SD 7+ Gen 3: CORES=3-7 THREADS=5 ./run.sh model.gguf
THREADS="${THREADS:-6}"
CTX="${CTX:-2048}"
if [[ -n "${CORES:-}" ]] && command -v taskset >/dev/null 2>&1; then
  exec taskset -c "${CORES}" llama-cli \
    -m "${MODEL}" \
    --no-mmap \
    --flash-attn auto \
    -t "${THREADS}" \
    -ngl 0 \
    -c "${CTX}" "$@"
fi
exec llama-cli -m "${MODEL}" \
  -t "${THREADS}" \
  --no-mmap \
  --flash-attn auto \
  -ngl 0 \
  -c "${CTX}" "$@"
RUNEOF
      ;;
  esac
  chmod +x "${vdir}/run.sh"
}

# ── uninstall ─────────────────────────────────────────────────────────────────
if [[ "${UNINSTALL}" == "1" ]]; then
  [[ "${DRY_RUN}" == "1" ]] && log "DRY RUN — nothing will be deleted"

  # "cpu" only ever means the wrapper dir — removing it doesn't touch gpu/,
  # which may still be wanted on its own. Uninstalling "gpu" (or "all") still
  # cascades to cpu/ below, since cpu can't function without gpu anyway.
  if [[ "${SELECT}" == "cpu" ]]; then
    CPU_DIR="${BASE_DIR}/cpu"
    if [[ ! -d "${CPU_DIR}" ]]; then
      warn "cpu: not installed — skipping"
    elif [[ "${DRY_RUN}" == "1" ]]; then
      printf '    remove %s\n' "${CPU_DIR}"
    else
      rm -rf "${CPU_DIR}"
      log "Removed ${CPU_DIR}"
    fi
    exit 0
  fi

  rm_path() {
    local p="$1"
    [[ -e "$p" || -L "$p" ]] || return 0
    if [[ "${DRY_RUN}" == "1" ]]; then
      printf '    remove %s\n' "$p"
    else
      rm -rf "$p"
    fi
    removed=$((removed + 1))
  }

  removed=0
  for VARIANT in "${VARIANTS[@]}"; do
    VDIR="$(dir_for "${VARIANT}")"
    BACKUP_DIR="$(backup_for "${VARIANT}")"

    if [[ ! -d "${VDIR}" ]]; then
      warn "${VARIANT}: not installed — skipping"
      continue
    fi

    tag="unknown"
    [[ -f "${VDIR}/lib/llama-cpp.version" ]] && tag=$(cat "${VDIR}/lib/llama-cpp.version")
    log "Uninstalling ${VARIANT} (${tag}) from ${VDIR}"

    rm_path "${VDIR}"
    [[ "${KEEP_BACKUP}" == "0" ]] && rm_path "${BACKUP_DIR}"

    # cpu/ has no binaries of its own — it's a wrapper around gpu/, so it
    # goes when gpu does.
    [[ "${VARIANT}" == "opencl" ]] && rm_path "${BASE_DIR}/cpu"
  done

  if [[ -d "${BASE_DIR}" && -z "$(ls -A "${BASE_DIR}" 2>/dev/null)" ]]; then
    if [[ "${DRY_RUN}" == "1" ]]; then
      printf '    rmdir  %s (empty)\n' "${BASE_DIR}"
    else
      rmdir "${BASE_DIR}" 2>/dev/null || true
    fi
  fi

  if [[ "${removed}" == "0" ]]; then
    warn "Nothing found to remove (already uninstalled?)"
  else
    log "Done — removed ${removed} item(s)."
  fi

  exit 0
fi

# ── backup ────────────────────────────────────────────────────────────────────
if [[ "${BACKUP}" == "1" ]]; then
  command -v zip >/dev/null 2>&1 || die "Missing: zip  (install with: pkg install zip)"
  [[ -n "${BACKUP_FILE}" ]] || BACKUP_FILE="${HOME}/llama-cpp-backup-$(date +%Y%m%d-%H%M%S).zip"

  [[ -d "${BASE_DIR}" ]] || die "Nothing installed to back up"

  log "Backing up: $(basename "${BASE_DIR}")"
  ( cd "${HOME}" && zip -rq "${BACKUP_FILE}" "$(basename "${BASE_DIR}")" )
  log "Backup written to ${BACKUP_FILE}"
  exit 0
fi

# ── restore ───────────────────────────────────────────────────────────────────
if [[ "${RESTORE}" == "1" ]]; then
  command -v unzip >/dev/null 2>&1 || die "Missing: unzip  (install with: pkg install unzip)"
  [[ -f "${RESTORE_FILE}" ]] || die "Backup file not found: ${RESTORE_FILE}"

  log "Restoring ${RESTORE_FILE} into ${HOME}"
  unzip -oq "${RESTORE_FILE}" -d "${HOME}"

  for VARIANT in "${VARIANTS[@]}"; do
    VDIR="$(vdir_for_variant "${VARIANT}")"
    [[ -d "${VDIR}/bin" ]] && chmod +x "${VDIR}/bin"/llama-* 2>/dev/null || true
  done
  log "Restore complete."
  exit 0
fi

# ── revert ────────────────────────────────────────────────────────────────────
if [[ "${REVERT}" == "1" ]]; then
  for VARIANT in "${VARIANTS[@]}"; do
    VDIR="$(vdir_for_variant "${VARIANT}")"
    INSTALL_DIR="${VDIR}/bin"
    LIB_DIR="${VDIR}/lib"
    BACKUP_DIR="$(backup_for "${VARIANT}")"

    if [[ ! -d "${BACKUP_DIR}" ]]; then
      warn "${VARIANT}: no backup found in ${BACKUP_DIR} — skipping"
      continue
    fi

    prev="unknown"
    [[ -f "${BACKUP_DIR}/llama-cpp.version" ]] && prev=$(cat "${BACKUP_DIR}/llama-cpp.version")
    log "${VARIANT}: reverting to ${prev}"

    mkdir -p "${INSTALL_DIR}" "${LIB_DIR}"
    cp "${BACKUP_DIR}"/bin/* "${INSTALL_DIR}/" 2>/dev/null || die "${VARIANT}: backup has no binaries"
    cp "${BACKUP_DIR}"/lib/*.so "${LIB_DIR}/" 2>/dev/null || true
    [[ -f "${BACKUP_DIR}/llama-cpp.version" ]] && cp "${BACKUP_DIR}/llama-cpp.version" "${LIB_DIR}/llama-cpp.version"
    chmod +x "${INSTALL_DIR}"/llama-* 2>/dev/null || true

    if [[ "${VARIANT}" == "opencl" && "${SELECT}" == "cpu" ]]; then
      [[ -f "${VDIR}/env.sh" ]] || write_env_script opencl "${VDIR}" cpu
      [[ -f "${VDIR}/run.sh" ]] || write_run_script cpu "${VDIR}"
    elif [[ "${VARIANT}" == "opencl" ]]; then
      [[ -f "${VDIR}/env.sh" ]] || write_env_script opencl "${VDIR}" gpu
      [[ -f "${VDIR}/run.sh" ]] || write_run_script opencl "${VDIR}"
      CPU_DIR="${BASE_DIR}/cpu"
      if [[ ! -f "${CPU_DIR}/run.sh" ]]; then
        mkdir -p "${CPU_DIR}"
        write_env_script opencl "${CPU_DIR}" "cpu, via gpu build" ../gpu
        write_run_script cpu "${CPU_DIR}"
      fi
    else
      [[ -f "${VDIR}/env.sh" ]] || write_env_script hexagon "${VDIR}" npu
      [[ -f "${VDIR}/run.sh" ]] || write_run_script hexagon "${VDIR}"
    fi

    rm -rf "${BACKUP_DIR}"
    log "${VARIANT}: reverted to ${prev}"
  done
  exit 0
fi

# ── fetch release info (once, shared by both variants) ────────────────────────
log "Fetching latest release info for ${REPO}"
release=$(curl -fsSL "https://api.github.com/repos/${REPO}/releases/latest")
tag=$(printf '%s' "${release}" | grep '"tag_name"' | head -n1 | sed 's/.*"tag_name": *"\(.*\)".*/\1/')
[[ -n "${tag}" ]] || die "Could not parse release tag — does the repo have any releases?"
log "Latest release: ${tag}"

for VARIANT in "${VARIANTS[@]}"; do
  VDIR="$(vdir_for_variant "${VARIANT}")"
  INSTALL_DIR="${VDIR}/bin"
  LIB_DIR="${VDIR}/lib"
  VERSION_FILE="${LIB_DIR}/llama-cpp.version"
  BACKUP_DIR="$(backup_for "${VARIANT}")"

  url=$(printf '%s' "${release}" | grep '"browser_download_url"' | grep '\.tar\.gz"' \
          | grep -- "-${VARIANT}-" | head -n1 | sed 's/.*"browser_download_url": *"\(.*\)".*/\1/')
  sha_url=$(printf '%s' "${release}" | grep '"browser_download_url"' | grep '\.tar\.gz\.sha256"' \
          | grep -- "-${VARIANT}-" | head -n1 | sed 's/.*"browser_download_url": *"\(.*\)".*/\1/')
  [[ -n "${url}" ]] || die "No '${VARIANT}' .tar.gz asset in release ${tag}"

  if [[ "${UPDATE}" == "1" ]]; then
    current="none"
    [[ -f "${VERSION_FILE}" ]] && current=$(cat "${VERSION_FILE}")
    if [[ "${current}" == "${tag}" ]]; then
      log "${VARIANT}: already up to date (${tag})"
      continue
    fi
    log "${VARIANT}: updating ${current} → ${tag}"
    if [[ -f "${INSTALL_DIR}/llama-cli" ]]; then
      rm -rf "${BACKUP_DIR}"
      mkdir -p "${BACKUP_DIR}/bin" "${BACKUP_DIR}/lib"
      for b in "${INSTALL_DIR}"/llama-*; do [[ -f "$b" ]] && cp "$b" "${BACKUP_DIR}/bin/"; done
      for l in "${LIB_DIR}"/*.so;     do [[ -f "$l" ]] && cp "$l" "${BACKUP_DIR}/lib/"; done
      [[ -f "${VERSION_FILE}" ]] && cp "${VERSION_FILE}" "${BACKUP_DIR}/"
    fi
  fi

  log "${VARIANT}: downloading $(basename "${url}")"
  mkdir -p "${INSTALL_DIR}" "${LIB_DIR}"
  tmp=$(mktemp -d)

  curl -fsSL --progress-bar "${url}" -o "${tmp}/llama.tar.gz"

  if [[ -n "${sha_url}" ]] && command -v sha256sum >/dev/null 2>&1; then
    curl -fsSL "${sha_url}" -o "${tmp}/llama.tar.gz.sha256"
    expected=$(awk '{print $1}' "${tmp}/llama.tar.gz.sha256")
    actual=$(sha256sum "${tmp}/llama.tar.gz" | awk '{print $1}')
    [[ "${expected}" == "${actual}" ]] || die "${VARIANT}: checksum mismatch (expected ${expected}, got ${actual})"
  fi

  tar -xzf "${tmp}/llama.tar.gz" -C "${tmp}"
  [[ -d "${tmp}/bin" && -d "${tmp}/lib" ]] || die "${VARIANT}: unexpected archive layout (no bin/ + lib/)"

  bins=( "${tmp}"/bin/llama-* )
  [[ ${#bins[@]} -gt 0 ]] || die "${VARIANT}: no llama-* binaries found in archive"
  cp "${bins[@]}" "${INSTALL_DIR}/"

  libs=( "${tmp}"/lib/*.so )
  [[ ${#libs[@]} -gt 0 ]] && cp "${libs[@]}" "${LIB_DIR}/"

  chmod +x "${INSTALL_DIR}"/llama-* 2>/dev/null || true
  printf '%s' "${tag}" > "${VERSION_FILE}"
  rm -rf "${tmp}"

  if [[ "${VARIANT}" == "opencl" && "${SELECT}" == "cpu" ]]; then
    # Selected cpu alone: these binaries ARE the cpu install, no gpu/ involved.
    write_env_script opencl "${VDIR}" cpu
    write_run_script cpu "${VDIR}"
  elif [[ "${VARIANT}" == "opencl" ]]; then
    write_env_script opencl "${VDIR}" gpu
    write_run_script opencl "${VDIR}"
    # cpu/ is free — just two wrapper scripts reusing these binaries in
    # CPU-only mode. Drop any stray bin/lib left behind by an earlier
    # standalone `install.sh cpu` so it doesn't sit there unused.
    CPU_DIR="${BASE_DIR}/cpu"
    rm -rf "${CPU_DIR}/bin" "${CPU_DIR}/lib"
    mkdir -p "${CPU_DIR}"
    write_env_script opencl "${CPU_DIR}" "cpu, via gpu build" ../gpu
    write_run_script cpu "${CPU_DIR}"
  else
    write_env_script hexagon "${VDIR}" npu
    write_run_script hexagon "${VDIR}"
  fi

  log "${VARIANT}: installed → ${VDIR}"
done

GPU_DIR="$(dir_for opencl)"
NPU_DIR="$(dir_for hexagon)"
CPU_DIR="${BASE_DIR}/cpu"

echo
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  llama.cpp ${tag} installed"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo
[[ -d "${GPU_DIR}" ]] && echo "  ${GPU_DIR}   CPU + OpenCL (Adreno GPU)"
[[ -d "${NPU_DIR}" ]] && echo "  ${NPU_DIR}   CPU + OpenCL + Hexagon NPU (HTP)"
[[ -d "${CPU_DIR}" ]] && echo "  ${CPU_DIR}   CPU only (reuses the gpu build, -ngl 0)"
echo
echo "── Quick start: run.sh <model.gguf> [llama-cli args...] ─"
[[ -d "${NPU_DIR}" ]] && echo "  ${NPU_DIR}/run.sh model-Q4_0.gguf -p \"Hello\""
[[ -d "${GPU_DIR}" ]] && echo "  ${GPU_DIR}/run.sh model.gguf -p \"Hello\""
[[ -d "${CPU_DIR}" ]] && echo "  ${CPU_DIR}/run.sh model.gguf -p \"Hello\""
echo
if [[ -d "${GPU_DIR}" || -d "${CPU_DIR}" ]]; then
  TUNE_DIR="${GPU_DIR}"; [[ -d "${GPU_DIR}" ]] || TUNE_DIR="${CPU_DIR}"
  echo "  Defaults are tunable via env vars, e.g.:"
  echo "    CORES=2-7 THREADS=4 ${TUNE_DIR}/run.sh model.gguf"
  echo "  See docs/USAGE.md for per-SoC CORES/THREADS values."
  echo
fi
echo "── Manual: source env.sh, then call llama-cli directly ──"
echo "Source (not run) a variant's env.sh to put its tools on plain PATH"
echo "(llama-cli, llama-server, ...) for the current shell session."
echo
if [[ -d "${NPU_DIR}" ]]; then
  echo "  source ${NPU_DIR}/env.sh"
  echo '  llama-cli -m model-Q4_0.gguf --device HTP0 -ngl 99 -c 4096 -p "Hello"'
  echo
fi
if [[ -d "${GPU_DIR}" ]]; then
  echo "  source ${GPU_DIR}/env.sh"
  echo '  taskset -c 2-7 llama-cli -m model.gguf -t 4 -ngl 28 -c 4096 -p "Hello"'
  echo
elif [[ -d "${CPU_DIR}" ]]; then
  echo "  source ${CPU_DIR}/env.sh"
  echo '  taskset -c 2-7 llama-cli -m model.gguf -t 6 -ngl 0 -c 2048 -p "Hello"'
  echo
fi
if [[ -d "${GPU_DIR}" || -d "${NPU_DIR}" || -d "${CPU_DIR}" ]]; then
  echo "── Server (OpenAI-compatible API) ───────────────────────"
  [[ -d "${NPU_DIR}" ]] && echo '  llama-server -m model.gguf --host 0.0.0.0 --port 8080 --device HTP0 -ngl 99'
  [[ -d "${GPU_DIR}" ]] && echo '  llama-server -m model.gguf --host 0.0.0.0 --port 8080 -t 4 -ngl 28 -c 4096'
  [[ ! -d "${GPU_DIR}" && -d "${CPU_DIR}" ]] && echo '  llama-server -m model.gguf --host 0.0.0.0 --port 8080 -t 6 -ngl 0 -c 2048'
  echo
fi
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
